config/routes.rb
Rails.application.routes.draw do
  

   root 'dealerships#index'

   resources :dealerships

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :dealership
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :dealership
  has_many :cars
end

app/models/dealership.rb
class Dealership < ActiveRecord::Base
	has_many :customers
	has_many :cars
	has_many :salesmen
end

app/models/salesman.rb
class Salesman < ActiveRecord::Base
  belongs_to :dealership
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/dealerships_controller.rb
class DealershipsController < ApplicationController
  def index
  	@dealerships = Dealership.all
  end

  def show
  	@dealership = Dealership.find(params[:id])
  	@cars = @dealership.cars
  	@customers = @dealership.customers

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dealerships_helper.rb
module DealershipsHelper
end

app/views/dashboard/index.html.haml
%h1 Dashboard#index
%p Find me in app/views/dashboard/index.html.haml

app/views/dealerships/index.html.haml
%h1 Dealerships
-if @dealerships.any?
	-@dealerships.each do |dealership|
		%ul 
		%h5= link_to dealership.name, dealership_path(dealership)

app/views/dealerships/show.html.haml
%h1.blue-text= @dealership.name
%h3.blue-text Cars
%hr
	.row
		- @cars.each do |car|
			.col.s12.m2
				.card.blue-grey.darken-1
					.card-content.white-text
						%span.card-title
							= car.make
							= car.model
						%p
							= "color: #{car.color}"
							= "$#{car.price}"
							= "Sold: #{car.sold}"
	%h3.blue-text Customers
	%hr
		.row
			- @customers.each do |customer|
				.col.s12.m2
					.card.blue.darken-1
						.card-content.white-text
							%span.card-title
								= customer.first_name
								= customer.last_name
							%p
								=customer.phone_number
								=customer.email
								


			
							

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Car Dealership
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
		= javascript_include_tag 'application', 'data-turbolinks-track' => true 
		= csrf_meta_tags 
	%body
		= yield


  	